//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gw2_Launchbuddy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool use_priority {
            get {
                return ((bool)(this["use_priority"]));
            }
            set {
                this["use_priority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Diagnostics.ProcessPriorityClass priority {
            get {
                return ((global::System.Diagnostics.ProcessPriorityClass)(this["priority"]));
            }
            set {
                this["priority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool use_autologin {
            get {
                return ((bool)(this["use_autologin"]));
            }
            set {
                this["use_autologin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int selected_acc {
            get {
                return ((int)(this["selected_acc"]));
            }
            set {
                this["selected_acc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cinema_imagepath {
            get {
                return ((string)(this["cinema_imagepath"]));
            }
            set {
                this["cinema_imagepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cinema_maskpath {
            get {
                return ((string)(this["cinema_maskpath"]));
            }
            set {
                this["cinema_maskpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cinema_musicpath {
            get {
                return ((string)(this["cinema_musicpath"]));
            }
            set {
                this["cinema_musicpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cinema_use {
            get {
                return ((bool)(this["cinema_use"]));
            }
            set {
                this["cinema_use"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cinema_video {
            get {
                return ((bool)(this["cinema_video"]));
            }
            set {
                this["cinema_video"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cinema_slideshow {
            get {
                return ((bool)(this["cinema_slideshow"]));
            }
            set {
                this["cinema_slideshow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cinema_videopath {
            get {
                return ((string)(this["cinema_videopath"]));
            }
            set {
                this["cinema_videopath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public double mediaplayer_volume {
            get {
                return ((double)(this["mediaplayer_volume"]));
            }
            set {
                this["mediaplayer_volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFE6E6E6")]
        public global::System.Windows.Media.Color cinema_backgroundcolor {
            get {
                return ((global::System.Windows.Media.Color)(this["cinema_backgroundcolor"]));
            }
            set {
                this["cinema_backgroundcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cinema_loginwindowpath {
            get {
                return ((string)(this["cinema_loginwindowpath"]));
            }
            set {
                this["cinema_loginwindowpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int cinema_slideshowendpos {
            get {
                return ((int)(this["cinema_slideshowendpos"]));
            }
            set {
                this["cinema_slideshowendpos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.205")]
        public double cinema_slideshowendscale {
            get {
                return ((double)(this["cinema_slideshowendscale"]));
            }
            set {
                this["cinema_slideshowendscale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double instance_win_X {
            get {
                return ((double)(this["instance_win_X"]));
            }
            set {
                this["instance_win_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double instance_win_Y {
            get {
                return ((double)(this["instance_win_Y"]));
            }
            set {
                this["instance_win_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int counter_launches {
            get {
                return ((int)(this["counter_launches"]));
            }
            set {
                this["counter_launches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool notifylbupdate {
            get {
                return ((bool)(this["notifylbupdate"]));
            }
            set {
                this["notifylbupdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useinstancegui {
            get {
                return ((bool)(this["useinstancegui"]));
            }
            set {
                this["useinstancegui"] = value;
            }
        }
    }
}
