//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gw2_Launchbuddy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cinema_imagepath {
            get {
                return ((string)(this["cinema_imagepath"]));
            }
            set {
                this["cinema_imagepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cinema_maskpath {
            get {
                return ((string)(this["cinema_maskpath"]));
            }
            set {
                this["cinema_maskpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cinema_musicpath {
            get {
                return ((string)(this["cinema_musicpath"]));
            }
            set {
                this["cinema_musicpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cinema_use {
            get {
                return ((bool)(this["cinema_use"]));
            }
            set {
                this["cinema_use"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cinema_video {
            get {
                return ((bool)(this["cinema_video"]));
            }
            set {
                this["cinema_video"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cinema_slideshow {
            get {
                return ((bool)(this["cinema_slideshow"]));
            }
            set {
                this["cinema_slideshow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cinema_videopath {
            get {
                return ((string)(this["cinema_videopath"]));
            }
            set {
                this["cinema_videopath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public double mediaplayer_volume {
            get {
                return ((double)(this["mediaplayer_volume"]));
            }
            set {
                this["mediaplayer_volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color cinema_backgroundcolor {
            get {
                return ((global::System.Windows.Media.Color)(this["cinema_backgroundcolor"]));
            }
            set {
                this["cinema_backgroundcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cinema_loginwindowpath {
            get {
                return ((string)(this["cinema_loginwindowpath"]));
            }
            set {
                this["cinema_loginwindowpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int cinema_slideshowendpos {
            get {
                return ((int)(this["cinema_slideshowendpos"]));
            }
            set {
                this["cinema_slideshowendpos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.205")]
        public double cinema_slideshowendscale {
            get {
                return ((double)(this["cinema_slideshowendscale"]));
            }
            set {
                this["cinema_slideshowendscale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int counter_launches {
            get {
                return ((int)(this["counter_launches"]));
            }
            set {
                this["counter_launches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool notifylbupdate {
            get {
                return ((bool)(this["notifylbupdate"]));
            }
            set {
                this["notifylbupdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useinstancegui {
            get {
                return ((bool)(this["useinstancegui"]));
            }
            set {
                this["useinstancegui"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ui_selectedtab {
            get {
                return ((int)(this["ui_selectedtab"]));
            }
            set {
                this["ui_selectedtab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useloadingui {
            get {
                return ((bool)(this["useloadingui"]));
            }
            set {
                this["useloadingui"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double mainwin_pos_x {
            get {
                return ((double)(this["mainwin_pos_x"]));
            }
            set {
                this["mainwin_pos_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double mainwin_pos_y {
            get {
                return ((double)(this["mainwin_pos_y"]));
            }
            set {
                this["mainwin_pos_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double mainwin_size_x {
            get {
                return ((double)(this["mainwin_size_x"]));
            }
            set {
                this["mainwin_size_x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double mainwin_size_y {
            get {
                return ((double)(this["mainwin_size_y"]));
            }
            set {
                this["mainwin_size_y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> plugins_toremove {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["plugins_toremove"]));
            }
            set {
                this["plugins_toremove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> plugins_todelete {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["plugins_todelete"]));
            }
            set {
                this["plugins_todelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> plugins_toinstall {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["plugins_toinstall"]));
            }
            set {
                this["plugins_toinstall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> plugins_toupdate {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["plugins_toupdate"]));
            }
            set {
                this["plugins_toupdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool plugins_autoupdate {
            get {
                return ((bool)(this["plugins_autoupdate"]));
            }
            set {
                this["plugins_autoupdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,150,300")]
        public string instancegui_windowsettings {
            get {
                return ((string)(this["instancegui_windowsettings"]));
            }
            set {
                this["instancegui_windowsettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool instancegui_ispinned {
            get {
                return ((bool)(this["instancegui_ispinned"]));
            }
            set {
                this["instancegui_ispinned"] = value;
            }
        }
    }
}
